norm:
  # PileUp_Lumi_MC:
  #   expression: weight_base_pu{scale}_rel  * final_weight
  #   name: CMS_pileup_{}
  MuonID_SF_Iso_ID:
    expression: weight_mu1_MuonID_SF_{muIso_WP_for_SF}PFIso_{muID_WP_for_SF}ID{scale}_rel * weight_mu2_MuonID_SF_{muIso_WP_for_SF}PFIso_{muID_WP_for_SF}ID{scale}_rel * final_weight
    name: CMS_eff_m_id_iso_{}
  MuonID_SF_ID:
    expression: weight_mu1_MuonID_SF_{muID_WP_for_SF}ID_Trk{scale}_rel * weight_mu2_MuonID_SF_{muID_WP_for_SF}ID_Trk{scale}_rel * final_weight
    name: CMS_eff_m_id_{}
  HLT_singleMu:
    expression: weight_TrgSF_singleMu_IsoMu24{scale}_rel * final_weight
    name: CMS_trig_singleMu_{}


shape:
  JES_Total:
    name: CMS_scale_j_{}
  JER:
    name: CMS_res_j_{}
  ScaRe:
    name: CMS_ScaRe_mu_{}
