triggerFile: config/Run3_2024/triggers.yaml
nano_version: v15
nanoAODVersions:
  data: v15
  mc: v15
ignore_missing_nanoAOD_files:
  data: False
  signals: True
  backgrounds: True
bTagAlgo: UParTAK4
corrections:
  btag:
    stages: [ AnaTuple, AnalysisCache, HistTuple ]
    modes:
      AnaTuple: none
      AnalysisCache: none
      HistTuple: none
    tagger: UParTAK4
    jetCollection: Jet
  mu:
    stage: HistTuple # AnaTuple
    columns:
      pfRelIso04_all: pfRelIso04_all
      tightId: tightId
      tkRelIso: tkRelIso
      highPtId: highPtId
      mediumId: mediumId
      looseId: looseId
      p4: p4 # it is the final ScaRe corrected p4, either BSC or nano according to chi2 --> has to be modified with the non-corrected pT
    lowPt: True
    midPt: True
    hiPt: False
  trigger:
    stages: HistTuple # AnaTuple
    mode: SF
    extraFormat:
      pt: "bsConstrainedPt"
  muScaRe:
    stages: [ AnaTuple, AnalysisCache, HistTuple ]
    scare_enabled:
      AnaTuple: true
      AnalysisCache: false
      HistTuple: false
    fsr_enabled:
      AnaTuple: false
      AnalysisCache: true
      HistTuple: true
    mu_pt_for_ScaReApplication: "bsConstrainedPt"
  lumi: { stage: AnaTuple }
  xs: { stage: AnaTuple }
  gen: { stage: AnaTuple }
  pu:
    stages: [ AnaTuple, AnaTupleMerge ]
    enabled:
      AnaTuple: true
      AnaTupleMerge: false
  base: { stage: AnaTupleMerge }
  JEC: { stage: AnaTuple }
  JER:
    stage: AnaTuple
    apply_jet_horns_fix: true
