# =========================
# GENERAL CONFIG
# =========================

anaTupleDef: AnaProd/anaTupleDef.py
histTupleDef: Analysis/histTupleDef.py
analysis_import: Analysis.H_mumu

phys_model: BaseModel
treeName: Events

# =========================
# COMPUTING / WLCG
# =========================

WLCGFileSystem:
  remotePathCacheHost: cms-flaf.cern.ch
  remotePathCachePort: 5000
  localPathCacheValidity: 600
  verbose: 0

runTokenServer:
  host: cms-flaf.cern.ch
  port: 5007

signal_types:
  - ggH
  - VBFH
#  - ttH
#  - VH

storeFatJets: False
met_type: "PuppiMET"

nEventsPerFile:
  data: 1000000
  signals: 1000000
  backgrounds: 1000000

channelSelection: [ muMu ]

# =========================
# CHANNELS
# =========================
channels:
  selection: [ muMu ]

  definition:
    muMu: "true"


# =========================
# REGIONS
# =========================
regions:
  MuMuMassRegions:
    Z_sideband: "m_mumu_ScaRe_FSR > 70 && m_mumu_ScaRe_FSR < 110"
    Signal_Fit: "m_mumu_ScaRe_FSR > 115 && m_mumu_ScaRe_FSR < 135"
    H_sideband: "((m_mumu_ScaRe_FSR > 110 && m_mumu_ScaRe_FSR < 115) || (m_mumu_ScaRe_FSR > 135 && m_mumu_ScaRe_FSR < 150))"
    Signal_ext: "m_mumu_ScaRe_FSR > 110 && m_mumu_ScaRe_FSR < 150"
    mass_inclusive: "m_mumu_ScaRe_FSR > 60 && m_mumu_ScaRe_FSR < 150"

# =========================
# TRIGGERS
# =========================
# triggers:
#   muMu:
#     default: "(HLT_singleMu)"

triggers:
  muMu: [ singleMu ]

hist_triggers:
  muMu:
    default: "(HLT_singleMu)"

singleMu_th:
  Run2_2016: 26
  Run2_2017: 29
  Run3_2022: 26
  Run3_2022EE: 26
  Run3_2023: 26
  Run3_2023BPix: 26
  Run3_2024: 26
  Run3_2025: 26

# =========================
# MUONS
# =========================
muons:
# noCorr
# ScaRe
# ScaRe_FSR
  pt_for_selection: pt_ScaRe_FSR
  ID_WP: Medium
  Iso_WP: Loose
  pt_for_TrgSFEvaluation: pt_noCorr
  extraFormat_for_triggerMatchingAndSF:
    pt: "bsConstrainedPt" # to fix

categories_to_select:
  - baseline
  - VBF
  - ggF
  
categories:
  muon_pre_sel_check: "mu1_{mu_pt_for_selection} > 15 && abs(mu1_eta) < 2.4 && mu2_{mu_pt_for_selection} > 15 && abs(mu2_eta) < 2.4"
  no_cuts: "muon_pre_sel_check"
  OS_sel: "muon_pre_sel_check && OS"
  trigger_sel: "( HLT_singleMu && ( ( mu1_{mu_pt_for_selection} > {MuPtTh} && mu1_HasMatching_singleMu) || (mu2_{mu_pt_for_selection} > {MuPtTh} && mu2_HasMatching_singleMu) ) ) " # official
  jets_cleanFromMu_sel: "JetTagSel"

  mu1_pt_l30: "mu1_{mu_pt_for_selection} < 30"
  mu2_pt_l30: "mu2_{mu_pt_for_selection} < 30"
  mu1_pt_g20: "mu1_{mu_pt_for_selection} > 20"
  mu2_pt_g20: "mu2_{mu_pt_for_selection} > 20"
  mu_pt_sel: "mu1_pt_g20 && mu2_pt_g20"

  base_sel: "trigger_sel && OS_sel && jets_cleanFromMu_sel"

  mu1_ML: "mu1_pfIsoId >= 2 && mu1_mediumId"
  mu1_LL: "mu1_pfIsoId >= 2 && mu1_looseId"
  mu1_TT: "mu1_pfIsoId >= 4 && mu1_tightId"
  mu2_ML: "mu2_pfIsoId >= 2 && mu2_mediumId"
  mu2_LL: "mu2_pfIsoId >= 2 && mu2_looseId"
  mu2_TT: "mu2_pfIsoId >= 4 && mu2_tightId"
  bothMuons_ML: "mu1_ML && mu2_ML"
  bothMuons_LL: "mu1_LL && mu2_LL"

  chi2_sel: "mu1_bsConstrainedChi2 < 30 && mu2_bsConstrainedChi2 < 30"
  pt_lessthan30_and_TT: "(((mu1_pt_l30 && mu1_TT) || !(mu1_pt_l30)) && ((mu2_pt_l30 && mu2_TT) || !(mu2_pt_l30)))"

  baseline: "base_sel && mu1_ML && mu2_ML"
  # baseline_thirdLepVeto: "baseline && vetoed_muons==0"
  baseline_chi2: "baseline && chi2_sel"
  baseline_lowPtTT: "(baseline) && (pt_lessthan30_and_TT)"

  # baseline_thirdLepVeto_chi2: "baseline && chi2_sel && vetoed_muons==0"
  # baseline_thirdLepVeto_lowPtTT: "baseline && (pt_lessthan30_and_TT) && vetoed_muons==0"
  baseline_chi2_lowPtTT: "baseline && (pt_lessthan30_and_TT) && chi2_sel"
  # baseline_thirdLepVeto_lowPtTT_chi2: "baseline && (pt_lessthan30_and_TT) && chi2_sel && vetoed_muons==0"

  # j1_outside_horn: "(abs(j1_eta) < 2.5 || abs(j1_eta) > 3 || j1_pt > 50)"
  # j2_outside_horn: "(abs(j2_eta) < 2.5 || abs(j2_eta) > 3 || j2_pt > 50)"
  VBF_def: "HasVBF && j1_pt >= 35 && j2_pt >= 25 && (abs(j1_eta) < 2.5 || abs(j1_eta) > 3 || j1_pt > 50) && (abs(j2_eta) < 2.5 || abs(j2_eta) > 3 || j2_pt > 50)"

  VBF: "baseline && VBF_def"
  ggF: "baseline && !(VBF_def)"
  # # VBF_thirdLepVeto: "baseline_thirdLepVeto && VBF_def"
  # # ggF_thirdLepVeto: "baseline_thirdLepVeto && !(VBF_def)"
  VBF_chi2: "baseline_chi2 && VBF_def"
  ggF_chi2: "baseline_chi2 && !(VBF_def)"
  VBF_lowPtTT: "baseline_lowPtTT && VBF_def"
  ggF_lowPtTT: "baseline_lowPtTT && !(VBF_def)"
  # # VBF_thirdLepVeto_chi2: "baseline_thirdLepVeto_chi2 && VBF_def"
  # # ggF_thirdLepVeto_chi2: "baseline_thirdLepVeto_chi2 && !(VBF_def)"
  VBF_chi2_lowPtTT: "baseline_chi2_lowPtTT && VBF_def"
  ggF_chi2_lowPtTT: "baseline_chi2_lowPtTT && !(VBF_def)"
  # # VBF_thirdLepVeto_lowPtTT: "baseline_thirdLepVeto_lowPtTT && VBF_def"
  # # ggF_thirdLepVeto_lowPtTT: "baseline_thirdLepVeto_lowPtTT && !(VBF_def)"
  # # VBF_thirdLepVeto_lowPtTT_chi2: "baseline_thirdLepVeto_lowPtTT_chi2 && VBF_def"
  # # ggF_thirdLepVeto_lowPtTT_chi2: "baseline_thirdLepVeto_lowPtTT_chi2 && !(VBF_def)"

  # mu1_prompt: "(mu1_genPartIdx >= 0 && mu1_gen_kind == 2)"
  # mu2_prompt: "(mu2_genPartIdx >= 0 && mu2_gen_kind == 2)"
  # mu1_from_tau: "(mu1_genPartIdx >= 0 && mu1_gen_kind == 4)"
  # mu2_from_tau: "(mu2_genPartIdx >= 0 && mu2_gen_kind == 4)"
  # both_muons_true_prompt: "mu1_prompt && mu2_prompt"
  # at_least_one_muon_from_tau: "!(both_muons_true_prompt) && (mu1_from_tau || mu2_from_tau)"
  # any_muon_not_true: "!(both_muons_true_prompt) && !(at_least_one_muon_from_tau)"


further_cuts: { }

# =========================
# CORRECTIONS
# =========================
corrections:
  btag:
    stages: [ AnaTuple, AnalysisCache, HistTuple ]
    modes:
      AnaTuple: none
      AnalysisCache: none
      HistTuple: none
    tagger: particleNet
    jetCollection: Jet
  mu:
    stage: HistTuple # AnaTuple
    columns:
      pfRelIso04_all: pfRelIso04_all
      tightId: tightId
      tkRelIso: tkRelIso
      highPtId: highPtId
      mediumId: mediumId
      looseId: looseId
      p4: p4 # it is the final ScaRe corrected p4, either BSC or nano according to chi2 --> has to be modified with the non-corrected pT
    lowPt: True
    midPt: True
    hiPt: False
  trigger:
    stages: HistTuple # AnaTuple
    mode: SF
    extraFormat:
      pt: "bsConstrainedPt"
  muScaRe:
    stages: [ AnaTuple, AnalysisCache, HistTuple ]
    scare_enabled:
      AnaTuple: true
      AnalysisCache: false
      HistTuple: false
    fsr_enabled:
      AnaTuple: false
      AnalysisCache: true
      HistTuple: true
    mu_pt_for_ScaReApplication: "bsConstrainedPt"
  lumi: { stage: AnaTuple }
  xs: { stage: AnaTuple }
  gen: { stage: AnaTuple }
  pu:
    stages: [ AnaTuple, AnaTupleMerge ]
    enabled:
      AnaTuple: true
      AnaTupleMerge: false
  base: { stage: AnaTupleMerge }
  JEC: { stage: AnaTuple }
  JER:
    stage: AnaTuple
    apply_jet_horns_fix: true


# =========================
# SCALES
# =========================
scales: [ Up, Down ]

ApplyBweight: false


payload_producers:
  DNN:
    producers_module_name: Analysis.DNN_Application
    producer_name: DNNProducer
    columns:
      - NNOutput
    n_cpus: 4
    max_runtime: 2.0
    cmssw_env: False
    awkward_based: True
    uproot_stepsize: '50MB'
    dependencies: [ ]
  VBFNet:
    producers_module_name: Analysis.VBFNet_Application
    producer_name: VBFNetProducer
    columns:
      - NNOutput
    n_cpus: 4
    max_runtime: 2.0
    cmssw_env: False
    awkward_based: True
    uproot_stepsize: '50MB'
    dependencies: [ ]
  PostVBFNetDNN:
    producers_module_name: Analysis.PostVBFNetDNN_Application
    producer_name: PostVBFNetDNNProducer
    columns:
      - NNOutput
    n_cpus: 4
    max_runtime: 2.0
    cmssw_env: False
    awkward_based: True
    uproot_stepsize: '50MB'
    dependencies: [ ]
