.DY_processors_allFlavors: &DY_processors_allFlavors
  - name: Stitcher
    module: FLAF.Processors.MCStitching
    class: MCStitcher
    config: FLAF/config/Processors/stitching_DY_amcatnlo_Vpt_NpNLO_allFlavors.yaml
    stages: [ AnaTuple, AnaTupleMerge ]
    verbose: 1
    dependency_level:
      AnaTuple: file
      AnaTupleMerge: process

.DY_processors_singleFlavor: &DY_processors_singleFlavor
  - name: Stitcher
    module: FLAF.Processors.MCStitching
    class: MCStitcher
    config: FLAF/config/Processors/stitching_DY_amcatnlo_Vpt_NpNLO.yaml
    stages: [ AnaTuple, AnaTupleMerge ]
    dependency_level:
      AnaTuple: file
      AnaTupleMerge: process

.ext_processor: &ext_processor
  - name: Stitcher
    verbose: 1
    module: FLAF.Processors.MCStitching
    class: MCStitcher
    useDatasetCrossSection: True
    stages: [ AnaTuple, AnaTupleMerge ]
    dependency_level:
      AnaTuple: file
      AnaTupleMerge: process
