name: Test Setup Loading

on:
  pull_request:
    types: [ "opened", "synchronize", "reopened", "labeled" ]
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test-setup-loading:
    uses: cms-flaf/FLAF/.github/workflows/test-setup-loading.yaml@main
    with:
      eras: "Run3_2022 Run3_2022EE Run3_2023 Run3_2023BPix Run3_2024 Run3_2025"
    secrets: inherit
